CREATE TYPE "gender_type" AS ENUM (
  'male',
  'female',
  'other'
);

CREATE TYPE "training_type" AS ENUM (
  'university',
  'bootcamp',
  'technological',
  'autodidact',
  'other'
);

CREATE TYPE "link_type" AS ENUM (
  'frontend',
  'backend',
  'demo',
  'docs',
  'other'
);

CREATE TYPE "role_type" AS ENUM (
  'full_stack',
  'frontend',
  'backend',
  'dev_ops',
  'junior',
  'semi_senior',
  'senior',
  'other'
);

CREATE TABLE "users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "first_name" varchar,
  "second_name" varchar,
  "first_surname" varchar,
  "second_surname" varchar,
  "nick_name" varchar,
  "phone" varchar,
  "email" varchar UNIQUE NOT NULL,
  "gender" gender_type NOT NULL,
  "abstract_user" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "profiles" (
  "id_profile" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_imagen" int NOT NULL,
  "id_user" int UNIQUE NOT NULL,
  "biography" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "social_networks" (
  "id_social_network" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_profile" int NOT NULL,
  "id_networks_type" int NOT NULL,
  "url" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "networks_type" (
  "id_network_type" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "icon_url" varchar
);

CREATE TABLE "experiences" (
  "id_profile" int NOT NULL,
  "id_experience" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "educations" (
  "id_profile" int NOT NULL,
  "id_education" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "description" text,
  "type_education" training_type,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "projects" (
  "id_project" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_user" int NOT NULL,
  "title" varchar,
  "description" text,
  "project_start_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "languages" (
  "id_language" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_languages" (
  "id_project" int NOT NULL,
  "id_language" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("id_project", "id_language")
);

CREATE TABLE "tools" (
  "id_tool" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_tools" (
  "id_project" int NOT NULL,
  "id_tool" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("id_project", "id_tool")
);

CREATE TABLE "project_links" (
  "id_link" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_project" int NOT NULL,
  "url" varchar NOT NULL,
  "type" link_type,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_roles" (
  "id_project" int NOT NULL,
  "id_role" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("id_project", "id_role")
);

CREATE TABLE "roles" (
  "id_role" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" role_type
);

CREATE TABLE "imagenes_project" (
  "id_project" int NOT NULL,
  "id_imagen" int NOT NULL,
  "default_position" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("id_project", "id_imagen")
);

CREATE TABLE "imagenes" (
  "id_imagen" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "path" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "certificates" (
  "id_certificate" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_profile" int NOT NULL,
  "id_imagen" int NOT NULL,
  "title" varchar,
  "issuer" varchar,
  "issued_date" timestamp,
  "credencial_url" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

COMMENT ON TABLE "users" IS 'Tabla para la identificacion del usuario';

COMMENT ON COLUMN "users"."first_name" IS 'Primer nombre';

COMMENT ON COLUMN "users"."second_name" IS 'Segundo nombre';

COMMENT ON COLUMN "users"."first_surname" IS 'Primer apellido';

COMMENT ON COLUMN "users"."second_surname" IS 'Segundo apellido';

COMMENT ON COLUMN "users"."nick_name" IS 'Avatar';

COMMENT ON COLUMN "users"."phone" IS 'Telefono de contacto';

COMMENT ON COLUMN "users"."email" IS 'Correo del usuario';

COMMENT ON COLUMN "users"."gender" IS 'Genero del usuario';

COMMENT ON COLUMN "users"."abstract_user" IS 'Resumen biografico del usuario';

COMMENT ON COLUMN "users"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "users"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "profiles" IS 'Informacion del usuario';

COMMENT ON COLUMN "profiles"."biography" IS 'Biografia';

COMMENT ON COLUMN "profiles"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "profiles"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "social_networks" IS 'Diferentes redes sociales';

COMMENT ON COLUMN "social_networks"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "social_networks"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "networks_type" IS 'Tabla catalogo para redes sociales';

COMMENT ON TABLE "experiences" IS 'Experiencia del usuario en la programacion';

COMMENT ON COLUMN "experiences"."description" IS 'Experiencia con la programacion';

COMMENT ON COLUMN "experiences"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "experiences"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "educations" IS 'Educacion del usuario en la programacion';

COMMENT ON COLUMN "educations"."description" IS 'Grado de estudio';

COMMENT ON COLUMN "educations"."type_education" IS 'Tipo de aprendizaje en la progracion obtenida';

COMMENT ON COLUMN "educations"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "educations"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "projects" IS 'Proyectos realizados por el usuario';

COMMENT ON COLUMN "projects"."title" IS 'Titulo del proyecto';

COMMENT ON COLUMN "projects"."description" IS 'Descripcion del proyecto';

COMMENT ON COLUMN "projects"."project_start_date" IS 'Fecha del proyecto';

COMMENT ON COLUMN "projects"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "projects"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "languages" IS 'Lenguaje de programacion utilizado en el proyecto';

COMMENT ON COLUMN "languages"."name" IS 'Nombre del lenguaje';

COMMENT ON COLUMN "languages"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "languages"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "project_languages" IS 'Tabla intermedia para representar la relación muchos a muchos entre proyectos y lenguajes de programación';

COMMENT ON COLUMN "project_languages"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "project_languages"."updated_at" IS 'Fecha de actualizacion';

COMMENT ON TABLE "tools" IS 'Herramientas utilizadas en el proyecto';

COMMENT ON COLUMN "tools"."name" IS 'Nombre de la herramienta (ej. React, Tailwind, Docker)';

COMMENT ON COLUMN "tools"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "tools"."updated_at" IS 'Fecha de actualización';

COMMENT ON TABLE "project_tools" IS 'Herramientas utilizadas en un proyecto (relación muchos a muchos)';

COMMENT ON COLUMN "project_tools"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "project_tools"."updated_at" IS 'Fecha de actualización';

COMMENT ON TABLE "project_links" IS 'Enlaces asociados a un proyecto (frontend, backend, demo, etc.)';

COMMENT ON COLUMN "project_links"."url" IS 'Enlace del proyecto';

COMMENT ON COLUMN "project_links"."type" IS 'Tipo de enlace (ej. frontend, backend, demo, docs)';

COMMENT ON COLUMN "project_links"."description" IS 'Descripción adicional del enlace';

COMMENT ON COLUMN "project_links"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "project_links"."updated_at" IS 'Fecha de actualización';

COMMENT ON TABLE "project_roles" IS 'Rol en el proyecto';

COMMENT ON COLUMN "project_roles"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "project_roles"."updated_at" IS 'Fecha de actualización';

COMMENT ON COLUMN "imagenes_project"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "imagenes_project"."updated_at" IS 'Fecha de actualización';

COMMENT ON COLUMN "imagenes"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "imagenes"."updated_at" IS 'Fecha de actualización';

COMMENT ON COLUMN "certificates"."issuer" IS 'Instituto';

COMMENT ON COLUMN "certificates"."created_at" IS 'Fecha de registro';

COMMENT ON COLUMN "certificates"."updated_at" IS 'Fecha de actualización';

ALTER TABLE "profiles" ADD FOREIGN KEY ("id_imagen") REFERENCES "imagenes" ("id_imagen");

ALTER TABLE "profiles" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user");

ALTER TABLE "social_networks" ADD FOREIGN KEY ("id_profile") REFERENCES "profiles" ("id_profile");

ALTER TABLE "social_networks" ADD FOREIGN KEY ("id_networks_type") REFERENCES "networks_type" ("id_network_type");

ALTER TABLE "experiences" ADD FOREIGN KEY ("id_profile") REFERENCES "profiles" ("id_profile");

ALTER TABLE "educations" ADD FOREIGN KEY ("id_profile") REFERENCES "profiles" ("id_profile");

ALTER TABLE "projects" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id_user");

ALTER TABLE "project_languages" ADD FOREIGN KEY ("id_project") REFERENCES "projects" ("id_project");

ALTER TABLE "project_languages" ADD FOREIGN KEY ("id_language") REFERENCES "languages" ("id_language");

ALTER TABLE "project_tools" ADD FOREIGN KEY ("id_project") REFERENCES "projects" ("id_project");

ALTER TABLE "project_tools" ADD FOREIGN KEY ("id_tool") REFERENCES "tools" ("id_tool");

ALTER TABLE "project_links" ADD FOREIGN KEY ("id_project") REFERENCES "projects" ("id_project");

ALTER TABLE "project_roles" ADD FOREIGN KEY ("id_project") REFERENCES "projects" ("id_project");

ALTER TABLE "project_roles" ADD FOREIGN KEY ("id_role") REFERENCES "roles" ("id_role");

ALTER TABLE "imagenes_project" ADD FOREIGN KEY ("id_project") REFERENCES "projects" ("id_project");

ALTER TABLE "imagenes_project" ADD FOREIGN KEY ("id_imagen") REFERENCES "imagenes" ("id_imagen");

ALTER TABLE "certificates" ADD FOREIGN KEY ("id_profile") REFERENCES "profiles" ("id_profile");

ALTER TABLE "certificates" ADD FOREIGN KEY ("id_imagen") REFERENCES "imagenes" ("id_imagen");
