# Generated by Django 4.2.23 on 2025-06-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, db_comment='Instituto', null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('credencial_url', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id_education', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_comment='Grado de estudio', null=True)),
                ('type_education', models.TextField(blank=True, db_comment='Tipo de aprendizaje en la progracion obtenida', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'educations',
                'db_table_comment': 'Educacion del usuario en la programacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id_experience', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, db_comment='Experiencia con la programacion', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'experiences',
                'db_table_comment': 'Experiencia del usuario en la programacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('path', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id_language', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Nombre del lenguaje', unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'languages',
                'db_table_comment': 'Lenguaje de programacion utilizado en el proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworksType',
            fields=[
                ('id_network_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('icon_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'networks_type',
                'db_table_comment': 'Tabla catalogo para redes sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('biography', models.TextField(blank=True, db_comment='Biografia', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'profiles',
                'db_table_comment': 'Informacion del usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(db_comment='Enlace del proyecto')),
                ('type', models.TextField(blank=True, db_comment='Tipo de enlace (ej. frontend, backend, demo, docs)', null=True)),
                ('description', models.TextField(blank=True, db_comment='Descripción adicional del enlace', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'project_links',
                'db_table_comment': 'Enlaces asociados a un proyecto (frontend, backend, demo, etc.)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_comment='Titulo del proyecto', null=True)),
                ('description', models.TextField(blank=True, db_comment='Descripcion del proyecto', null=True)),
                ('project_start_date', models.DateTimeField(blank=True, db_comment='Fecha del proyecto', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'projects',
                'db_table_comment': 'Proyectos realizados por el usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id_social_network', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'social_networks',
                'db_table_comment': 'Diferentes redes sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id_tool', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Nombre de la herramienta (ej. React, Tailwind, Docker)', unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'tools',
                'db_table_comment': 'Herramientas utilizadas en el proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_comment='Primer nombre', null=True)),
                ('second_name', models.CharField(blank=True, db_comment='Segundo nombre', null=True)),
                ('first_surname', models.CharField(blank=True, db_comment='Primer apellido', null=True)),
                ('second_surname', models.CharField(blank=True, db_comment='Segundo apellido', null=True)),
                ('nick_name', models.CharField(blank=True, db_comment='Avatar', null=True)),
                ('phone', models.CharField(blank=True, db_comment='Telefono de contacto', null=True)),
                ('email', models.CharField(db_comment='Correo del usuario', unique=True)),
                ('gender', models.TextField(db_comment='Genero del usuario')),
                ('abstract_user', models.TextField(blank=True, db_comment='Resumen biografico del usuario', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'Tabla para la identificacion del usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProject',
            fields=[
                ('id_project', models.OneToOneField(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.projects')),
                ('default_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'imagenes_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLanguages',
            fields=[
                ('id_project', models.OneToOneField(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.projects')),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualizacion', null=True)),
            ],
            options={
                'db_table': 'project_languages',
                'db_table_comment': 'Tabla intermedia para representar la relación muchos a muchos entre proyectos y lenguajes de programación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRoles',
            fields=[
                ('id_project', models.OneToOneField(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.projects')),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'project_roles',
                'db_table_comment': 'Rol en el proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTools',
            fields=[
                ('id_project', models.OneToOneField(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.projects')),
                ('created_at', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Fecha de actualización', null=True)),
            ],
            options={
                'db_table': 'project_tools',
                'db_table_comment': 'Herramientas utilizadas en un proyecto (relación muchos a muchos)',
                'managed': False,
            },
        ),
    ]
